name: Post Release - Prepare Main for Next Development Cycle

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.1)'
        required: true

jobs:
  prepare-main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Determine release branch and checkout
        run: |
          VERSION="${{ github.event.inputs.version }}"
          MAJOR_MINOR=$(echo $VERSION | awk -F. '{print $1"."$2}')
          RELEASE_BRANCH="release/${MAJOR_MINOR}.x"
          git fetch origin $RELEASE_BRANCH
          git checkout -b "prepare-main-for-next-dev-cycle-${VERSION}" origin/$RELEASE_BRANCH

      - name: Update version to next development version in main
        run: |
          DEV_VERSION="${{ github.event.inputs.version }}.dev0"
          sed -i 's/__version__ = ".*"/__version__ = "'$DEV_VERSION'"/' aws-opentelemetry-distro/src/amazon/opentelemetry/distro/version.py
          git add aws-opentelemetry-distro/src/amazon/opentelemetry/distro/version.py
          git commit -m "Prepare main for next development cycle: Update version to $DEV_VERSION"
          git push --set-upstream origin "prepare-main-for-next-dev-cycle-${VERSION}"

      - name: Create Pull Request to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "prepare-main-for-next-dev-cycle-${VERSION}"
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Prepare main for next development cycle: Update version to $DEV_VERSION"
          pr_body: "This PR prepares the main branch for the next development cycle by updating the version to $DEV_VERSION.\n\nBy submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice."
